"""Render the cohort's track from a submissions checkout.

    uv run python scripts/track.py --from ../dev3pack-submissions-2026-09
    uv run python scripts/track.py --from <checkout> --check   # fail if stale

TRANSPORT ONLY. The scores live in the submitted bundles and the shape lives in
`bootcamp_agent.track`. This file renders them, exactly as `course_index.py`
renders the curriculum, so the table cannot drift from the submissions it claims
to describe.

WHY IT WRITES INTO THE SUBMISSIONS CHECKOUT AND NOT THIS REPOSITORY. The track is
about student work, which lives there. This repository holds the harness and the
answers and must never learn who scored what.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from bootcamp_agent.track import Track, read_tree, submittable_items  # noqa: E402

BANNER = "<!-- generated by scripts/track.py — edit the submissions, not this file -->"


def render_markdown(track: Track) -> str:
    items = submittable_items()
    scored = [item for item in items if item.scored]

    lines = [
        BANNER,
        "",
        f"# Track — cohort {track.cohort}",
        "",
        f"{len(track.students)} students have handed something in, "
        f"across {len(scored)} marked chapters.",
        "",
        "A cell shows what that chapter was worth. `handed in` means the work was",
        "submitted and is not marked, which now means week 0 only: it is self-paced.",
        "Every session carries marks. Sessions 1 and 10 need an assistant open, so",
        "nothing can re-run them and their rows read `unverifiable` -- a fact about",
        "the item, never about the student. An empty cell means nothing has been",
        "submitted yet, which is not the same as a zero.",
        "",
    ]

    header = "| Student | " + " | ".join(item.id for item in items) + " | Total |"
    divider = "|---|" + "---|" * (len(items) + 1)
    lines += [header, divider]

    for github in track.students:
        by_item = track.by_student(github)
        cells = []
        for item in items:
            entry = by_item.get(item.id)
            cells.append(entry.cell if entry else "")
        earned, available = track.scored_total(github)
        lines.append(f"| {github} | " + " | ".join(cells) + f" | {earned}/{available} |")

    lines += ["", "## Per chapter", "", "| Chapter | Handed in | Marked |", "|---|---|---|"]
    for item in items:
        submitted = [e for e in track.entries if e.item == item.id]
        marked = "yes" if item.scored else f"no — {item.note or 'not marked'}"
        lines.append(f"| {item.id} | {len(submitted)} | {marked} |")

    week_zero = sorted(
        (e for e in track.entries if e.item.startswith("w")), key=lambda e: (e.github, e.item)
    )
    if week_zero:
        lines += [
            "",
            "## Week 0, handed in",
            "",
            "Self-paced and unmarked. It is here because the work was done, not because",
            "it counts.",
            "",
            "| Student | Units |",
            "|---|---|",
        ]
        for github in sorted({e.github for e in week_zero}):
            units = ", ".join(e.item for e in week_zero if e.github == github)
            lines.append(f"| {github} | {units} |")

    if track.problems:
        lines += ["", "## Bundles that could not be read", ""]
        lines += [f"- {problem}" for problem in track.problems]

    return "\n".join(lines) + "\n"


def render_json(track: Track) -> str:
    # `items` is the denominator. Without it a consumer cannot tell "not submitted"
    # from "handed in and never marked", and a blank cell has no shape.
    payload = {
        "schema": "dev3pack.track.v1",
        "cohort": track.cohort,
        "items": [
            {
                "id": item.id,
                "title": item.title,
                "scored": item.scored,
                "verifiable": item.verifiable,
                "max_score": item.max_score,
            }
            for item in submittable_items()
        ],
        "entries": [
            {
                "github": e.github,
                "item": e.item,
                "submitted_at": e.submitted_at,
                "ran": e.ran,
                "passed": list(e.passed),
                "failed": list(e.failed),
                "not_reached": list(e.not_reached),
                "scored": e.scored,
                "score": e.score,
                "max_score": e.max_score,
                "tier": e.tier,
            }
            for e in sorted(track.entries, key=lambda e: (e.github, e.item))
        ],
        "problems": list(track.problems),
    }
    return json.dumps(payload, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--from",
        dest="source",
        type=Path,
        required=True,
        help="a checkout of the submissions repository",
    )
    parser.add_argument("--cohort", default="2026-09")
    parser.add_argument("--check", action="store_true", help="fail if the rendered files are stale")
    args = parser.parse_args(argv)

    track = read_tree(args.source / "submissions", cohort=args.cohort)
    rendered = {
        args.source / "TRACK.md": render_markdown(track),
        args.source / "track.json": render_json(track),
    }

    if args.check:
        stale = [p for p, text in rendered.items() if not p.is_file() or p.read_text() != text]
        for path in stale:
            print(f"stale: {path}")
        if stale:
            print("\nre-run: uv run python scripts/track.py --from <checkout>")
            return 1
        print("the track is current")
        return 0

    for path, text in rendered.items():
        path.write_text(text)
        print(f"wrote {path}")
    print(f"{len(track.entries)} submissions from {len(track.students)} students")
    for problem in track.problems:
        print(f"  could not read: {problem}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
